language: cpp
before_script:
  - sudo apt-get install uuid-dev
  - sudo apt-get install libxml2-dev
  - wget http://googletest.googlecode.com/files/gtest-1.6.0.zip
  - unzip -q gtest-1.6.0.zip
  - cd gtest-1.6.0
  - sudo cmake . 
  - sudo make
  - cd ..
  - ls
  - cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_LIBRARY_PATH=gtest-1.6.0 -DCMAKE_INCLUDE_PATH=gtest-1.6.0/include .
script: 
  - sudo make
  - sudo make install
after_script: sudo make test
compiler:
  - gcc
env:
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG
    - CMAKE_BUILD_TYPE=RELEASE